### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by kneufeld** [fortress-shell/fortress-shell#1]
Are there any docs explaining how to install and what this is? The tiny animation isn't much to go on... I'm looking to auto-deploy to nomad from on-prem gitlab, can `fortress-shell` help me with that? No idea.

**Comment by moredure** [comment]
Hello, no, fortress-shell doesn't support deployment, just running tests inside virtual machine from fortress.yml into nomad. Also there is no support for Gitlab

**Comment by moredure** [comment]
Also this project, plus or minus, archived
